/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Main Menu
 *
 */
#define CONFIG_DRIVERS_GIC_V2 1
#define CONFIG_CMD_CD 1
#define CONFIG_KERNEL_VBASE 0xFFFF000001000000
#define CONFIG_RS_STACK_PAGES 8
#define CONFIG_SYS_TICK 62
#define CONFIG_TEST 1
#define CONFIG_XXX 1
#define CONFIG_MAX_PRIORITY 32
#define CONFIG_IRQ_COUNT 287
#define CONFIG_CPU0 1
#define CONFIG_DEFUALT_TIMESLICE 20
#define CONFIG_STACK_PAGES 2
#define CONFIG_KERNEL_PBASE 0x41000000
#define CONFIG_FORWARD_SMC 1
#define CONFIG_SMP 1
#define CONFIG_PLAT_QEMU_VIRT 1
#define CONFIG_KERNEL_NAME "Cinos"
#define CONFIG_PRINTD_LEVEL 3
#define CONFIG_PRIORITY_ROOTSERVER 8
#define CONFIG_CMD_CAT 1
#define CONFIG_RS_VBASE 0X60000000
#define CONFIG_KERNEL_VERSION "v2.0.0"
#define CONFIG_NR_CPUS 4
#define CONFIG_ARCH_CORTEXA55 1
#define CONFIG_ARCH_ARM64 1
#define CONFIG_ARCH_ARMV8_A 1
#define CONFIG_DEBUG 1
#define CONFIG_DEFAULT_PRIORITY 10
#define CONFIG_OPT_O0 1
